### ISSUE TITLE
local_config.py or local_settings.py?

### ISSUE THREAD

**Issue by HaamedKhosravii** [jamedadi/Divar#31]
According to the README.md, we must create `local_config.py` file for local configuration. Also all of the necessaries, has been imported from `local_config.py` file in `settings.py`. But in `.gitignore` file, `local_settings.py` has been ignored, instead. Which one of them I must create for configuration?
@PEMIDI

**Comment by PEMIDI** [comment]
> According to the README.md, we must create 'local_config.py' file for local configuration. Also all of the necessaries, has been imported from 'local_config.py' file in 'settings.py'. But in '.gitignore' file, 'local_settings.py' has been ignored, instead. Which one of them I must create for configuration? @PEMIDI

That is true. Because the ```local config.py``` file included security configurations for the project, I ignored it.
Simply insert the information into a ```local config.py``` file that you create on your machine.
@EngRobot33

**Comment by PEMIDI** [comment]
I merged some codes about your issue.

https://github.com/jamedadi/Divar/pull/32
